FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    openssh-server \
    python3 \
    python3-pip \
    ansible \
    git \
    sudo \
    openjdk-17-jre-headless \
    && mkdir -p /var/run/sshd

# user pentru Jenkins (va fi agent Jenkins)
RUN useradd -ms /bin/bash jenkins

# cheia publică a lui Jenkins pt acest container
COPY keys/jenkins_to_ansible.pub /home/jenkins/.ssh/authorized_keys

RUN chown -R jenkins:jenkins /home/jenkins/.ssh && \
    chmod 700 /home/jenkins/.ssh && \
    chmod 600 /home/jenkins/.ssh/authorized_keys

# cheia privată cu care Ansible se va conecta la test-server
COPY keys/ansible_to_test /home/jenkins/.ssh/ansible_to_test
RUN chown jenkins:jenkins /home/jenkins/.ssh/ansible_to_test && \
    chmod 600 /home/jenkins/.ssh/ansible_to_test

# configurăm sshd
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config && \
    sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/' /etc/ssh/sshd_config && \
    echo "AllowUsers jenkins" >> /etc/ssh/sshd_config

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
